name = "cloudflags"
main="src/index.tsx"
compatibility_date = "2023-01-01"
usage_model = "bundled"
workers_dev = false
kv_namespaces = [
    { binding = "KV", id = "3fcc62e639c04b9381c028fe6e85e844", preview_id = "3fcc62e639c04b9381c028fe6e85e844" }
]
routes = [
	{ pattern = "cloudflags.wcore.net/*", zone_name = "wcore.net" }
]


[site]
bucket = "./assets"